### ISSUE TITLE
Browser side @useContent error with Browserify

### ISSUE THREAD

**Issue by ghost** [krakenjs/dust-makara-helpers#8]
I'm trying to use client side localization so I'm requiring dust-makara-helpers with browserify as said in the project readme. 
The module is loaded with success but on client side on dust.render() of templates with @useContent I get this error:

Error: no view available rendering template named 'cluster' and content bundle 'cluster.properties'

ps: There is any other way to include helpers without using browserify like we do for dust-helpers? (e.g.: <script src="/components/dustjs-helpers/dist/dust-helpers.min.js" ></script>  )

**Comment by aredridel** [comment]
You can build AMD or stand-alone packages of the helpers with webpack to not use browserify.

Sounds a bit like you don't have the templates loaded -- what's your `dust.onLoad` ?

**Comment by ghost** [comment]
This is my  onLoad:

``` javascript
dust.onLoad = function(templateName, callback) {
  $.get('/templates/' + templateName + '.js', function(data) {
    dust.loadSource(data);
    callback();
  });
};
```

Without

``` javascript
require('dust-makara-helpers').registerWith(dust, {
    enableMetadata: true,
    autoloadTemplateContent: false
});
```

 everything works fine .

**Comment by aredridel** [comment]
Seems reasonable. You may want to call back with the output of loadSource, but should work.

What's the `templateName` of that template internally?

**Comment by aredridel** [comment]
(you're relying on the name in cache being a match)

**Comment by ghost** [comment]
It should be "cluster" , but I can't get it from the @contextDump full, there is no field regarding the templateName. 
Why am I relying on the name on cache? If I am right if I do not get an hit on cache i will load the template fro source using the template name used in dust.render('name').

**Comment by ghost** [comment]
Yes, the templateName it is "cluster" : 

``` javascript
dust.register("cluster",body_0);
```

**Comment by ghost** [comment]
Any news on this? Were you able to reproduce?

**Comment by aredridel** [comment]
I've not built a sample app to test in -- your setup is a little different than mine and I've been short on time. I can try to do that, but if you have a sample app I'd love to test in the same situation you are.

**Comment by ghost** [comment]
Here it is:
https://github.com/MikeQuaci/test-makara.git

Is there any tutorial/ blog article / git repository where you have shared your configuration for browser-side application?

**Comment by aredridel** [comment]
Hmm. that works for me (once I installed node-4.0.0-rc.1 -- something about node-sass with 0.12.7 for me) but the two display with no errors, useContent shows localization, no useContent shows snowman-greeting-snowman as it should.

**Comment by ghost** [comment]
Hmmm, so what's going on on my browsers? I'm on ubuntu 14.04 and both
firefox and chrome show the error on the useContent case.
Did you rebuilt my application? Or are you using the same sources committed
by me?
Il 05/set/2015 22:38, "Aria Stewart" notifications@github.com ha scritto:

**Comment by aredridel** [comment]
Good question!

I ran `npm install; npm start; npm install node-sass; npm rebuild; npm start`

**Comment by ghost** [comment]
No way to make it work,I still getting the error in console (showed below) when I click on useContent button.
I can't explain how it works for you and why you needed node-saas. It's a basic example made with kraken generator, I just had some bower dependencies, and 2 templates.

![Image of error](http://oi61.tinypic.com/n2jshu.jpg)

**Comment by aredridel** [comment]
Your screenshot is 403ed.

**Comment by ghost** [comment]
Sorry,it should be ok now.
If not try here https://drive.google.com/file/d/0ByS0J8sgEDYleVZFYU1WcXE3TVE/view?usp=sharing

**Comment by ghost** [comment]
Hi, please have a look here: http://188.226.201.33:8001/
It's the same app hosted. If you click on the first button you should get "Usecontet, usecontent-brws" in the first row , but instead you get this error in the console:

VError: no view available rendering template named 'partial-usecontent' and content bundle 'partial-usecontent.properties'

I have tested it from different browsers, and I get the same error everywhere.

The machine is running a docker container, the image can be find here: https://hub.docker.com/r/mikequaci/test-makara/

It's an image based on the official node:0.12.7-wheezy , with my "makara-test" app installed and running as follows:

$ git clone https://github.com/MikeQuaci/test-makara.git
$ cd test-makara
$ npm install
$ npm build
$ npm start

**Comment by ghost** [comment]
Sorry to bug you again about this, but do you have any news?

**Comment by aredridel** [comment]
Yeah, with those instructions I get this:

``````

> test-makara@0.1.0 start /Users/aredridel/Projects/test-makara
> node server.js

Server listening on http://localhost:8001
Application ready to serve requests.
Environment: development
Error: `libsass` bindings not found in /Users/aredridel/Projects/test-makara/node_modules/construx-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/aredridel/Projects/test-makara/node_modules/construx-sass/node_modules/node-sass/lib/extensions.js:150:11)
    at Object.<anonymous> (/Users/aredridel/Projects/test-makara/node_modules/construx-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/aredridel/Projects/test-makara/node_modules/construx-sass/index.js:21:11)
    at Module._compile (module.js:460:26)```
``````

**Comment by ghost** [comment]
I'm sorry but I think that your problem has nothing to do with my source code. It could be another bug relative consturx-sass and your system, those instructions do not show any error in other ubuntu systems. If you try them on a clean  [nodejs  docker image](https://hub.docker.com/_/node/) they will not throw any error.
Probably if you try to create new kraken.js app on your system with kraken generator selecting dust.js, sass, browserify and bower you will get the same error.

**Comment by ghost** [comment]
Finally I found out where is the problem, to track it down I had to change the package.json adding this entry:`"browser": "browser.js",` ([as required by browserify](https://github.com/substack/browserify-handbook#browser-field))
After that I got a different error  `Uncaught TypeError: lookup function must be in the form function(context, bundle, callback) { ... }` , and from there I was able to go on my own providing  a loader function to  `require('dust-makara-helpers').registerWith`.

Now it works also without the new entry on package.json , but I think it is still needed to load the correct script.

**Comment by grawk** [comment]
I've got a working example of server/browser render with browserify here: https://github.com/grawk/try18n/tree/browserify

I'm not clear from the comments here if you think there is any code change necessary in this module?

**Comment by grawk** [comment]
Closing due to inactivity
